### ISSUE TITLE
Re-post didn't occur when @forth@gup.pe tagged twice in post.

### ISSUE THREAD

**Issue by nonlinearzone** [wmurphyrd/guppe#16]
I've made three posts tagging @forth@gup.pe:

1. https://soliton.nonlinear.zone/notice/9priHDM5HlBhmgLQYa
2. https://soliton.nonlinear.zone/notice/9prjDk6HhJq08ZrYGG
3. https://soliton.nonlinear.zone/notice/9pro018u2PTEi3MW6C

The second one didn't re-post, and the only reason I suspect is that @forth@gup.pe was tagged twice in the post.

**Comment by wmurphyrd** [comment]
There's no record of that middle post ever being delivered to my guppe server. It's possible it was delivered, but hit an error during processing before it could be saved, but I don't see anything in the logs that looks like that

**Comment by nonlinearzone** [comment]
Okay, thanks for checking. I will let you know if it comes up again. 

Sent from my iPhone

> On Dec 14, 2019, at 1:46 PM, Will Murphy <notifications@github.com> wrote:
> 

﻿
There's no record of that middle post ever being delivered to my guppe server. It's possible it was delivered, but hit an error during processing before it could be saved, but I don't see anything in the logs that looks like that

**Comment by wmurphyrd** [comment]
Awesome. Please file another issue if you see it again.
