### ISSUE TITLE
Check that the group is actually an adressee before boosting

### ISSUE THREAD

**Issue by wmurphyrd** [wmurphyrd/guppe#17]
If someone untags the guppe group on a reply, the reply may still be delivered to guppe (e.g. Mastodon v3.0.1). Currently, guppe boosts all inbox activity, but it will need to verify the group appears in one of the address fields on the activity.

**Comment by wakest** [comment]
weird so looking at https://social.wake.st/@liaizon/103297303493710950.json this didn't mention guppe at all. So how did guppe even see it to reshare it?

**Comment by wmurphyrd** [comment]
@wakest the trigger for guppe groups to reshare right now is receiving any Create activity POSTed to an inbox. So, Mastodon must have delivered it anyway. Probably part of some processes in Mastodon to prevent broken threads
