### ISSUE TITLE
Thread support/Boost only the first post in the thread

### ISSUE THREAD

**Issue by drequivalent** [wmurphyrd/guppe#18]
Now, it looks like gup.pe boosts all posts, including replies.

That means, there is basically no notion of threads. It's like a chat or something.

Two years ago or so, I made a prototype bot, @rf@mastodonsocial.ru that announces posts only if two conditions are met:

a) the bot is mentioned
b) the post is the first in the thread, meaning there is no "InReplyTo" field

This, in my opinion, makes much more sense, as the front page becomes a catalog of threads, just like a forum would be:

https://mastodonsocial.ru/@rf

This works surprisingly well to this day

**Comment by wmurphyrd** [comment]
Thanks but a message board is not what I'm going for here.
