### ISSUE TITLE
Spotted it posting Personal Messages on the site

### ISSUE THREAD

**Issue by o-jasper** [wmurphyrd/guppe#20]
It cannot boost them, the web interface is intended to be the same as the fediverse profile, and most importantly, people don't expect this to happen.

**Comment by wmurphyrd** [comment]
Sorry. So a message was sent, tagging a Guppe group, but with non-public permissions? Could you explain what you do expect to happen in this circumstance?

**Comment by o-jasper** [comment]
If you hit PM people don't expect one of the participants to post it publicly, of course.. Especially if they don't even realize it's a bot.

**Comment by wmurphyrd** [comment]
Would you expect it to still deliver to other group subscribers without listing it on the public profile or just to ignore the message?

**Comment by o-jasper** [comment]
I think it should ignore PMs/Followers-only  toots. It shouldn't make things visible publicly that wouldn't normally be? Otherwise it might end up making a private conversation public if people forget to not-address the bot. (also it can't actually boost it so the site and the profile elsewhere might not match)

Of course PMs/etc might be able to do things, if it is explicit somehow.
