### ISSUE TITLE
No go for pleroma users?

### ISSUE THREAD

**Issue by buttle** [wmurphyrd/guppe#21]
Hi,

A couple of us (pleroma users) are not receiving post from groups. It seems the subscription is not completing properly. The request status remains at `Request sent`and 'toots' do not arrive.

We can see that the member count on the group profile page does increment when we (pleroma users) subscribe, and our posts are seen on that page. Our posts also arrive a Mastodon inboxes.

Any thoughts?

Thanks.

**Comment by wmurphyrd** [comment]
I've tested it successfully on pleroma in the past. Which groups are you seeing this with?

**Comment by buttle** [comment]
@fedicat and @admins_del_fediverso

**Comment by wmurphyrd** [comment]
I'll check the logs

**Comment by buttle** [comment]
Hi,

Could I help you test this? Please let know know :)

**Comment by GuDzpoz** [comment]
Having the same problem here. Is there any hope that this be fixed? Thanks!

Some probably relevant logs: 
```
$ sudo journalctl -f -u pleroma | grep gup.pe
                                          INSERT INTO "activities" ("actor","data","local","recipients","id","inserted_at","updated_at") VALUES ($1,$2,$3,$4,$5,$6,$7) ["https://wuppo.allowed.org/users/ShyKana", %{"actor" => "https://wuppo.allowed.org/users/ShyKana", "cc" => [], "id" => "https://wuppo.allowed.org/activities/0a6fba3f-d014-4fc4-a9cc-0d4b7f976d44", "object" => "https://gup.pe/u/rec", "state" => "pending", "to" => ["https://gup.pe/u/rec"], "type" => "Follow"}, true, ["https://gup.pe/u/rec"], <<0, 0, 1, 116, 103, 156, 86, 79, 247, 128, 197, 197, 156, 72, 0, 0>>, ~N[2020-09-07 08:08:53], ~N[2020-09-07 08:08:53]]
Sep 07 08:08:53 lil-wuppo pleroma[78642]: request_id=FjJx-UMGv75dx4wADhyR [debug] Fetching object https://gup.pe/u/rec/following via AP
Sep 07 08:08:53 lil-wuppo pleroma[78642]: request_id=FjJx-UMGv75dx4wADhyR [error] Follower/Following counter update for https://gup.pe/u/rec failed.
                                          SELECT u0."id", u0."bio", u0."raw_bio", u0."email", u0."name", u0."nickname", u0."password_hash", u0."keys", u0."public_key", u0."ap_id", u0."avatar", u0."local", u0."follower_address", u0."following_address", u0."tags", u0."last_refreshed_at", u0."last_digest_emailed_at", u0."banner", u0."background", u0."note_count", u0."follower_count", u0."following_count", u0."locked", u0."confirmation_pending", u0."password_reset_pending", u0."approval_pending", u0."registration_reason", u0."confirmation_token", u0."default_scope", u0."domain_blocks", u0."deactivated", u0."no_rich_text", u0."ap_enabled", u0."is_moderator", u0."is_admin", u0."show_role", u0."mastofe_settings", u0."uri", u0."hide_followers_count", u0."hide_follows_count", u0."hide_followers", u0."hide_follows", u0."hide_favorites", u0."unread_conversation_count", u0."pinned_activities", u0."email_notifications", u0."mascot", u0."emoji", u0."pleroma_settings_store", u0."fields", u0."raw_fields", u0."discoverable", u0."invisible", u0."allow_following_move", u0."skip_thread_containment", u0."actor_type", u0."also_known_as", u0."inbox", u0."shared_inbox", u0."accepts_chat_messages", u0."notification_settings", u0."blocks", u0."mutes", u0."muted_reblogs", u0."muted_notifications", u0."subscribers", u0."multi_factor_authentication_settings", u0."inserted_at", u0."updated_at" FROM "users" AS u0 WHERE (u0."ap_id" = ANY($1)) AND (u0."deactivated" != $2) AND (u0."local" = $3) AND (NOT (u0."nickname" IS NULL)) [["https://gup.pe/u/rec"], true, true]
                                          SELECT i0."host", i0."unreachable_since" FROM "instances" AS i0 WHERE (i0."host" = ANY($1)) [["gup.pe"]]
Sep 07 08:08:53 lil-wuppo pleroma[78642]: [debug] Federating https://wuppo.allowed.org/activities/0a6fba3f-d014-4fc4-a9cc-0d4b7f976d44 to https://gup.pe/u/rec/inbox
                                            Parameters: %{"@context" => ["https://www.w3.org/ns/activitystreams", "https://w3id.org/security/v1"], "actor" => "https://gup.pe/u/rec", "id" => "https://gup.pe/s/5f55ea957b7c067df2dcf43c", "nickname" => "ShyKana", "object" => %{"@context" => ["https://www.w3.org/ns/activitystreams", "https://wuppo.allowed.org/schemas/litepub-0.1.jsonld", %{"@language" => "und"}], "_meta" => %{"_target" => "https://gup.pe/u/rec"}, "actor" => "https://wuppo.allowed.org/users/ShyKana", "cc" => [], "id" => "https://wuppo.allowed.org/activities/0a6fba3f-d014-4fc4-a9cc-0d4b7f976d44", "object" => "https://gup.pe/u/rec", "state" => "pending", "to" => ["https://gup.pe/u/rec"], "type" => "Follow"}, "published" => "2020-09-07T08:08:53.922Z", "to" => ["https://wuppo.allowed.org/users/ShyKana"], "type" => "Accept"}
                                          SELECT i0."id", i0."host", i0."unreachable_since", i0."favicon", i0."favicon_updated_at", i0."inserted_at", i0."updated_at" FROM "instances" AS i0 WHERE (i0."host" = $1) ["gup.pe"]
Sep 07 08:08:54 lil-wuppo pleroma[78642]: request_id=FjJx-YQS4icHvnIADhzB [debug] Signature validation error for: https://gup.pe/u/rec, make sure you are forwarding the HTTP Host header!
Sep 07 08:08:54 lil-wuppo pleroma[78642]: request_id=FjJx-YQS4icHvnIADhzB [debug] [{"accept", "application/json"}, {"connection", "upgrade"}, {"content-length", "686"}, {"content-type", "application/activity+json"}, {"date", "Mon, 07 Sep 2020 08:08:53 GMT"}, {"host", "wuppo.allowed.org"}, {"signature", "keyId=\"https://gup.pe/u/rec\",algorithm=\"rsa-sha256\",headers=\"(request-target) host date\",signature=\"QdYIUO2QR6oeIBCNSLJbT79JqjH9+EigEbcv0dIwjnQvNAnO0fbuP5AbODbuDP+7p7teVNnZ22qr6u0/X0VUF9iDL5KusEUEbNnQfxX3QMP2IAljvLbm7GTKC/ReFueN7nacoXd0ZQQYPvoyQsa6mHCLqmDTcqMOCwq+/bDprD54m14RUkVHjo1ihCQRPFFG/QINnlSmnqwvlqV+QMNIvQ5CdeP23NY1JMgtnhLmCvzH3FySd0iZSaQe/Porjf48jehpt+uzQltFWFPnt9hD1zomS3pQLab2B1h6uk68K7hmN5eFe3YJ4/07WK3qr33LDtKWHI7odVHX2hF61t0JlDCsqjZBLmE9gtRZup2fJcQ1iEKqQ8GBH/wyoWdb+1DRXk2hsU1vk6AppnxYNsi9/jyXtlLmfSI4uhjRR4r2X+AUtsCVoHNLFFAZ5Frn0DJgvXtl82LYe/dGI76nlMJDnexwfTyKpdhTdNFQbTsHhuZzkmh9Qxd1dMZjjttyh7a45YnggeZQcMoL/g6lhY9tXdjRaRBUhhMbv68Lf53SdUvZ8QST32nJv8RrbhA+rhZqtUnrhkzCN8XsvdL9j3h+Cc/fBreE02/IvUvSHbiO151fbpZDWlg+3z7vTGmkpj5a5ZMgpN27sAwt85Av2Q015p9iceXG4FlqgvwS42CHFLU=\""}, {"x-forwarded-for", "162.249.4.153"}]
```

**Comment by wmurphyrd** [comment]
Thanks. This is helpful. I'll decode that signature and see why it failed validation 

On Mon, Sep 7, 2020, at 4:32 AM, gudzpoz wrote:
> 

> Having the same problem here. Is there any hope that this be fixed? Thanks!

> Some probably relevant logs:

> `$ sudo journalctl -f -u pleroma | grep gup.pe
                                          INSERT INTO "activities" ("actor","data","local","recipients","id","inserted_at","updated_at") VALUES ($1,$2,$3,$4,$5,$6,$7) ["https://wuppo.allowed.org/users/ShyKana", %{"actor" => "https://wuppo.allowed.org/users/ShyKana", "cc" => [], "id" => "https://wuppo.allowed.org/activities/0a6fba3f-d014-4fc4-a9cc-0d4b7f976d44", "object" => "https://gup.pe/u/rec", "state" => "pending", "to" => ["https://gup.pe/u/rec"], "type" => "Follow"}, true, ["https://gup.pe/u/rec"], <<0, 0, 1, 116, 103, 156, 86, 79, 247, 128, 197, 197, 156, 72, 0, 0>>, ~N[2020-09-07 08:08:53], ~N[2020-09-07 08:08:53]]
Sep 07 08:08:53 lil-wuppo pleroma[78642]: request_id=FjJx-UMGv75dx4wADhyR [debug] Fetching object https://gup.pe/u/rec/following via AP
Sep 07 08:08:53 lil-wuppo pleroma[78642]: request_id=FjJx-UMGv75dx4wADhyR [error] Follower/Following counter update for https://gup.pe/u/rec failed.
                                          SELECT u0."id", u0."bio", u0."raw_bio", u0."email", u0."name", u0."nickname", u0."password_hash", u0."keys", u0."public_key", u0."ap_id", u0."avatar", u0."local", u0."follower_address", u0."following_address", u0."tags", u0."last_refreshed_at", u0."last_digest_emailed_at", u0."banner", u0."background", u0."note_count", u0."follower_count", u0."following_count", u0."locked", u0."confirmation_pending", u0."password_reset_pending", u0."approval_pending", u0."registration_reason", u0."confirmation_token", u0."default_scope", u0."domain_blocks", u0."deactivated", u0."no_rich_text", u0."ap_enabled", u0."is_moderator", u0."is_admin", u0."show_role", u0."mastofe_settings", u0."uri", u0."hide_followers_count", u0."hide_follows_count", u0."hide_followers", u0."hide_follows", u0."hide_favorites", u0."unread_conversation_count", u0."pinned_activities", u0."email_notifications", u0."mascot", u0."emoji", u0."pleroma_settings_store", u0."fields", u0."raw_fields", u0."discoverable", u0."invisible", u0."allow_following_move", u0."skip_thread_containment", u0."actor_type", u0."also_known_as", u0."inbox", u0."shared_inbox", u0."accepts_chat_messages", u0."notification_settings", u0."blocks", u0."mutes", u0."muted_reblogs", u0."muted_notifications", u0."subscribers", u0."multi_factor_authentication_settings", u0."inserted_at", u0."updated_at" FROM "users" AS u0 WHERE (u0."ap_id" = ANY($1)) AND (u0."deactivated" != $2) AND (u0."local" = $3) AND (NOT (u0."nickname" IS NULL)) [["https://gup.pe/u/rec"], true, true]
                                          SELECT i0."host", i0."unreachable_since" FROM "instances" AS i0 WHERE (i0."host" = ANY($1)) [["gup.pe"]]
Sep 07 08:08:53 lil-wuppo pleroma[78642]: [debug] Federating https://wuppo.allowed.org/activities/0a6fba3f-d014-4fc4-a9cc-0d4b7f976d44 to https://gup.pe/u/rec/inbox
                                            Parameters: %{"@context" => ["https://www.w3.org/ns/activitystreams", "https://w3id.org/security/v1"], "actor" => "https://gup.pe/u/rec", "id" => "https://gup.pe/s/5f55ea957b7c067df2dcf43c", "nickname" => "ShyKana", "object" => %{"@context" => ["https://www.w3.org/ns/activitystreams", "https://wuppo.allowed.org/schemas/litepub-0.1.jsonld", %{"@language" => "und"}], "_meta" => %{"_target" => "https://gup.pe/u/rec"}, "actor" => "https://wuppo.allowed.org/users/ShyKana", "cc" => [], "id" => "https://wuppo.allowed.org/activities/0a6fba3f-d014-4fc4-a9cc-0d4b7f976d44", "object" => "https://gup.pe/u/rec", "state" => "pending", "to" => ["https://gup.pe/u/rec"], "type" => "Follow"}, "published" => "2020-09-07T08:08:53.922Z", "to" => ["https://wuppo.allowed.org/users/ShyKana"], "type" => "Accept"}
                                          SELECT i0."id", i0."host", i0."unreachable_since", i0."favicon", i0."favicon_updated_at", i0."inserted_at", i0."updated_at" FROM "instances" AS i0 WHERE (i0."host" = $1) ["gup.pe"]
Sep 07 08:08:54 lil-wuppo pleroma[78642]: request_id=FjJx-YQS4icHvnIADhzB [debug] Signature validation error for: https://gup.pe/u/rec, make sure you are forwarding the HTTP Host header!
Sep 07 08:08:54 lil-wuppo pleroma[78642]: request_id=FjJx-YQS4icHvnIADhzB [debug] [{"accept", "application/json"}, {"connection", "upgrade"}, {"content-length", "686"}, {"content-type", "application/activity+json"}, {"date", "Mon, 07 Sep 2020 08:08:53 GMT"}, {"host", "wuppo.allowed.org"}, {"signature", "keyId=\"https://gup.pe/u/rec\",algorithm=\"rsa-sha256\",headers=\"(request-target) host date\",signature=\"QdYIUO2QR6oeIBCNSLJbT79JqjH9+EigEbcv0dIwjnQvNAnO0fbuP5AbODbuDP+7p7teVNnZ22qr6u0/X0VUF9iDL5KusEUEbNnQfxX3QMP2IAljvLbm7GTKC/ReFueN7nacoXd0ZQQYPvoyQsa6mHCLqmDTcqMOCwq+/bDprD54m14RUkVHjo1ihCQRPFFG/QINnlSmnqwvlqV+QMNIvQ5CdeP23NY1JMgtnhLmCvzH3FySd0iZSaQe/Porjf48jehpt+uzQltFWFPnt9hD1zomS3pQLab2B1h6uk68K7hmN5eFe3YJ4/07WK3qr33LDtKWHI7odVHX2hF61t0JlDCsqjZBLmE9gtRZup2fJcQ1iEKqQ8GBH/wyoWdb+1DRXk2hsU1vk6AppnxYNsi9/jyXtlLmfSI4uhjRR4r2X+AUtsCVoHNLFFAZ5Frn0DJgvXtl82LYe/dGI76nlMJDnexwfTyKpdhTdNFQbTsHhuZzkmh9Qxd1dMZjjttyh7a45YnggeZQcMoL/g6lhY9tXdjRaRBUhhMbv68Lf53SdUvZ8QST32nJv8RrbhA+rhZqtUnrhkzCN8XsvdL9j3h+Cc/fBreE02/IvUvSHbiO151fbpZDWlg+3z7vTGmkpj5a5ZMgpN27sAwt85Av2Q015p9iceXG4FlqgvwS42CHFLU=\""}, {"x-forwarded-for", "162.249.4.153"}]
`

**Comment by umonaca** [comment]
Same here. I have created an issue at https://git.pleroma.social/pleroma/pleroma/-/issues/2266

**Comment by umonaca** [comment]
It does not work with latest stable version of Pleroma. I have figured out a fix while debugging the Pleroma server.

### Reason:
First, let's look at what gup.pe actually send to a Pleroma server:
![image](https://user-images.githubusercontent.com/53662960/97159833-ce8bf280-1751-11eb-9859-c5b0d7978747.png)

Be aware that Accept header is `application/json`, but `Content-Type` is `application/activity+json`.

In [Line 19](https://git.pleroma.social/pleroma/pleroma/-/blob/stable/lib/pleroma/plugs/http_signature.ex#L19) of this file, Pleroma uses the Phoenix framework to determine the content type. It is set in the config files of Pleroma:

> "application/activity+json" => ["activity+json"],
> "application/ld+json" => ["activity+json"]

However, for gup.pe `get_format` always returns `json` rather than `activity+json`, because for some reason the `Accept` header takes higher priority. Thus the Pleroma server simply skips the entire signature verification and jumps to [here](https://git.pleroma.social/pleroma/pleroma/-/blob/stable/lib/pleroma/web/activity_pub/activity_pub_controller.ex#L282)

### Solution:
Either remove the `Accept` header or set it to `application/activity+json`. Then it should work for Pleroma.

**Comment by umonaca** [comment]
I think that removing `json: true` and change `body` to `body: JSON.stringify(body)` should work.

**Comment by dduenker** [comment]
Is this issue the reason i can't seem to be able to subscribe to groups using pleroma?
I just get the following message from pleroma: "Error fetching user"

**Comment by ioistired** [comment]
@dduenker yes

**Comment by wmurphyrd** [comment]
Oh no this is still an issue? I saw Pleroma had [identified it as an issue on their end](https://git.pleroma.social/pleroma/pleroma/-/issues/2266#note_76077) and assumed they were going to fix, but now I see that is still open. In that case, we could put the proposed workaround in

**Comment by ioistired** [comment]
When I asked about it, I was told it was an issue on gup.pe's end and directed here :/

**Comment by wmurphyrd** [comment]
@umonaca I've fixed the header issue and also fixed another issue I found with how my JSON-LD processor was handling Pleroma's default language tag, yet it still doesn't seem to work on Pleroma. Any more debugging you'd be willing to do in the Pleroma side would be greatly appreciated (please note, the site was moved to https://a.gup.pe)

**Comment by wmurphyrd** [comment]
Just had a successful test from Pleroma 2.4.51 :tada: 

Please file new issues for any further pleroma trouble
