### ISSUE TITLE
Status showed on group profile page but not on local instance

### ISSUE THREAD

**Issue by Zerolemis** [wmurphyrd/guppe#23]
A really strange situation happened just now: Someone tagged a group in a [toot](https://botsin.space/@Zerolemis/103991909278414566 ) but it was not showed on my local instance (bgme.me). However, when I go to the group profile page, it's showed there. (FYI, I have followed both this account and the group account.) I wonder how does this happen?

**Comment by Zerolemis** [comment]
Will it affects if two group toots are posted in a very short time?

**Comment by wmurphyrd** [comment]
I think this was probably just a delivery issue. Please open new ticket if the issue persists
