### ISSUE TITLE
hello cant follow the group

### ISSUE THREAD

**Issue by zhaojundong99** [wmurphyrd/guppe#26]
hello 
in our mastodon instance https://me.ns.ci
i and my friends cant follow any gup.pe group
when click follow 
it shows send a follow request
and in admin panel the instance the Deliverable show false
What could be the problem
thx

**Comment by wmurphyrd** [comment]
Very strange - my server has no record of any POST requests from yours. I just created an account to test and all the GET requests to find the group work fine, but then nothing appears when I try to POST the follow request. 

I don't think this is unique to you, I've had some other reports of follows occasionally not working. I'll keep looking into it.

**Comment by wmurphyrd** [comment]
Do you have any logs from the failed delivery attempts?
