### ISSUE TITLE
[Feature] admin interface to moderate posts & adhesions

### ISSUE THREAD

**Issue by jibe-b** [wmurphyrd/guppe#27]
I love the hacks that gup.pe groups constitute!

An improvements would be to enable to login to gup.pe to administrate the group.

The group's account could be "locked" (= follow has to be accepted by the admin). Hence enabling to manage the list of followers.

Posts mentioning the group's account would be added to a queue, with buttons to accept of reject posts. The queue could only contains posts of accounts that have been accepted as followers.

This administration board would limit the way groups are created, it would need to login to gup.pe and create it there. Or indeed in any instance running the gup.pe software.

**Comment by wmurphyrd** [comment]
These are necessary features, but I won't be investing significant time in Guppe in the near future. 
Have you see what [QOTO has recently published for moderated groups](https://groups.qoto.org/about/more)?
