### ISSUE TITLE
[Compatibility] Need support for outbox pagination

### ISSUE THREAD

**Issue by umonaca** [wmurphyrd/guppe#30]
See:
https://github.com/tootsuite/mastodon/issues/15025

For now the user cannot search for some active groups from Mastodon, due to the outbox size limit. It's been fixed on their side on master branch, but it still takes months for it to go into stable releases.

**Comment by wmurphyrd** [comment]
Yeah I'm surprised it made it this far without pagination. Working on [activitypub-express](https://github.com/immers-space/activitypub-express) right now which will be used as the new core for guppe once it has pagination
