### ISSUE TITLE
Active groups never changed

### ISSUE THREAD

**Issue by umonaca** [wmurphyrd/guppe#31]
There are some groups such as @board@gup.pe which has 8000+ posts, but they never get listed in the Active Groups. Is it a bug in the code? Or do you need to manually refresh the results?

**Comment by wmurphyrd** [comment]
Must be a bug in the aggregation pipeline. I'll take a look when porting guppe over to [activitypub-express](https://github.com/immers-space/activitypub-express)

**Comment by wmurphyrd** [comment]
Fixed this a while ago
