### ISSUE TITLE
Support posting to multiple guppes

### ISSUE THREAD

**Issue by knobhead** [wmurphyrd/guppe#40]
Hi,
thanks for gup.pe!
I noticed that when you mention more than one gup.pe in a single toot, only the last mentioned retoots my toot. Ia that intended behaviour?
Regards

**Comment by wmurphyrd** [comment]
I can post to multiple groups at once and it shows up in the profile page of each group. However, in your timeline, Mastodon will only show the most recent boost of any given post (whether from a group or regular user).
