### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by xundeenergie** [wmurphyrd/guppe#41]
I don't know, how to find some infos, who is running the website https://gup.pe 
But this service is down since a few days.

Maybe i ruined it, because i tried to follow a gup.pe group as a friendica-forum... since this trial the gup.pe groups are not working any more...

**Comment by jiangshanghan** [comment]
now we can use ovo.st for instead.
here is the codes https://github.com/wxwmoe/wxwClub

**Comment by xundeenergie** [comment]
Gup.pe server was up yesterday, but it retootet nothing... today it's down again.

I checked my friendica forums... so the abonement of gup.pe groups have still been there... i think, this could really be the reason for gup.pes shutdown.

i removed all the followings in my friendica forums to gup.pe groups.

if someone would restart the server again... hopefully, it comes up again and retoots in future... and the devs will have a look after this problem. 
please feel free to contact me for tests!

**Comment by wmurphyrd** [comment]
When I put it back up on https://gup.pe, some Mastodon instances were ignoring it - they never attempted to POST the toots or follows to Guppe, so Guppe could never respond. 

At the moment, it is up & working at https://a.gup.pe

Trying to decide if we just settle for using the subdomain or if we try to figure out how to get Masto instances to resume working it the original domain

**Comment by xundeenergie** [comment]
did the private key for the system actor change?
in other words, did you delete the database and started again from stretch?

**Comment by aschrijver** [comment]
The website is running on a different domain (a sub-domain): https://a.gup.pe/

See @wmurphyrd post here:  https://social.coop/@datatitian/107430680542287482

**Comment by wmurphyrd** [comment]
> did the private key for the system actor change? in other words, did you delete the database and started again from stretch?

I did, but that's doesn't seem to be the issue because I wasn't getting 4xx back from Masto anywhere, the Mastodon instances were simply never attempting to POST to gup.pe when I tried to mention it. I think at this stage we just have to move on to the subdomain unless someone wants to take charge of this issue

**Comment by rugk** [comment]
Same confusion for me, BTW: https://github.com/wmurphyrd/guppe/issues/51 (also because the old domain still appears in the fediverse, which is kinda bad…)
