### ISSUE TITLE
nginx config

### ISSUE THREAD

**Issue by Tealk** [wmurphyrd/guppe#45]
Hello,

how can you use gup.pe behind a nginx proxy? I thought I can just use a `proxy_pass http://localhost:4431/;` and it would work but then I end up with 502 Bad Gateway

**Comment by wmurphyrd** [comment]
Will need add a config option for Guppe to run behind proxy. It'll need to do 2 things:
1. Set the Express 'trust proxy' mode
2. Don't try to start up the auto-certificate generator

An example of implementing this in another activitypub-express based project: https://github.com/immers-space/immers/pull/40/files

**Comment by Tealk** [comment]
thank you for the quick reply

means I have to apply all the changes indicated there?

**Comment by wmurphyrd** [comment]
These changes should be added here in the main guppe repo to open this feature to everyone. If you're game, I'd gladly accept a pull request with them. If not, I will find some time to do it

**Comment by Tealk** [comment]
I'll have a look but I'm not sure if I have the skills for it.

**Comment by wmurphyrd** [comment]
Proxy mode is available now, docs: https://github.com/wmurphyrd/guppe#optional-configuration
