### ISSUE TITLE
home page should show examples with the correct domain

### ISSUE THREAD

**Issue by autonompost** [wmurphyrd/guppe#50]
Examples at the front page are displayed with @YourGroupNameHere@a.gup.pe. This could be misleading, when the groups are actually created with another domain name, like groups.autonomy.earth 

https://groups.autonomy.earth/

**Comment by wmurphyrd** [comment]
Wow another guppe instance! That's awesome. I'll update this to respect the domain setting ASAP

**Comment by wmurphyrd** [comment]
New release has this fixed. Also added updating instructions: https://github.com/wmurphyrd/guppe#updating

**Comment by autonompost** [comment]
> Wow another guppe instance! That's awesome. I'll update this to respect the domain setting ASAP

Yea. There were no users using it yet, but I plan to install it again on another host
