### ISSUE TITLE
Server is down

### ISSUE THREAD

**Issue by rugk** [wmurphyrd/guppe#51]
https://gup.pe/ is down, no server can be reached.

https://www.isitdownrightnow.com/gup.pe.html

**Comment by wmurphyrd** [comment]
The app is located at https://a.gup.pe

I added a redirect to the apex domain

**Comment by rugk** [comment]
OKay well the redirect does not work: https://gup.pe/

**Comment by rugk** [comment]
Came here because some servers still use/cache (I guess?) the old domain and so I was using it accidentally:
https://mas.to/@blueplanetslittlehelper/108268223417157726

**Comment by implr** [comment]
+1, the redirect seems to be broken. We're getting a lot of failed attempts to connect to gup.pe on our instance.
