### ISSUE TITLE
I've created an inordinate amount of groups for an ongoing collaborative shitpost and you may wish to delete them at some point.

### ISSUE THREAD

**Issue by chexo3** [wmurphyrd/guppe#57]
Hello! I created a metric fuckload of groups for the [CVQcon2022 shitpost](https://lethargic.talkative.fish/@suricrasia/statuses/01GF6T11D0BVF6A3ZQW4ES0YYW) someone made up earlier today, and I'm done at this point.

You may wish to purge all of the groups created by myself (@Byte@rage.love) as the shitpost is getting dull and they are probably cluttering your database or panel or whatever.

Sorry for this dumb shitpost.

**Comment by wmurphyrd** [comment]
No problem
